"""Local-first runtime loop runner and worker adapters."""

from .action_plans import ActionPlan, build_action_plan, render_worker_prompt
from .codex_adapter import CodexAdapter, CodexInvocationResult
from .loop_runner import LoopRunner, LoopRunnerResult, handle_runtime_codex_loop, run_goal_loop
from .playground import PlaygroundWorkspace, persist_playground_summary, prepare_playground_workspace
from .repo_inspector import RepoInspectionResult, inspect_repo_state
from .repo_inspector import VerificationCommandResult
from .request_router import (
    RouteDecision,
    RouteResult,
    classify_request,
    handle_natural_language_request,
    route_goal_request,
    route_request,
)
from .response_contract import AriCliResponse, build_cli_response, render_cli_response
from .scenario_harness import (
    AcceptanceResult,
    ScenarioDefinition,
    ScenarioHarnessResult,
    ScenarioRunResult,
    handle_runtime_playground_run,
    handle_runtime_smoke_test,
    run_playground_goal,
    run_runtime_scenarios,
)
from .self_improvement_runner import (
    ControllerDecisionRecord,
    ImprovementSlice,
    SelfImprovementCycle,
    SelfImprovementRunResult,
    SelfImprovementRunner,
    SliceSelection,
    handle_runtime_self_improve,
    run_self_improvement_loop,
)
from .verification_profiles import (
    Check,
    FileChanged,
    NoUnexpectedChanges,
    OptionalCustomCheck,
    OutputMatches,
    SymbolExists,
    TestPasses,
    VerificationCheckResult,
    VerificationContext,
    VerificationProfile,
    VerificationResult,
    evaluate_profile,
    verification_profile_for_slice,
)
from .worker_backend import (
    CommandWorkerBackend,
    StubWorkerBackend,
    WorkerBackend,
    WorkerBackendMode,
    WorkerInvocationResult,
    resolve_worker_backend,
)

__all__ = [
    "CodexAdapter",
    "CodexInvocationResult",
    "ActionPlan",
    "AcceptanceResult",
    "Check",
    "CommandWorkerBackend",
    "ControllerDecisionRecord",
    "FileChanged",
    "ImprovementSlice",
    "LoopRunner",
    "LoopRunnerResult",
    "NoUnexpectedChanges",
    "OptionalCustomCheck",
    "OutputMatches",
    "PlaygroundWorkspace",
    "RepoInspectionResult",
    "AriCliResponse",
    "RouteDecision",
    "RouteResult",
    "ScenarioDefinition",
    "ScenarioHarnessResult",
    "ScenarioRunResult",
    "SymbolExists",
    "SelfImprovementCycle",
    "SelfImprovementRunResult",
    "SelfImprovementRunner",
    "SliceSelection",
    "TestPasses",
    "StubWorkerBackend",
    "VerificationCheckResult",
    "VerificationContext",
    "VerificationCommandResult",
    "VerificationProfile",
    "VerificationResult",
    "WorkerBackend",
    "WorkerBackendMode",
    "WorkerInvocationResult",
    "build_action_plan",
    "build_cli_response",
    "classify_request",
    "evaluate_profile",
    "handle_runtime_codex_loop",
    "handle_runtime_playground_run",
    "handle_runtime_smoke_test",
    "handle_runtime_self_improve",
    "handle_natural_language_request",
    "inspect_repo_state",
    "persist_playground_summary",
    "prepare_playground_workspace",
    "render_cli_response",
    "route_goal_request",
    "route_request",
    "render_worker_prompt",
    "resolve_worker_backend",
    "run_goal_loop",
    "run_playground_goal",
    "run_runtime_scenarios",
    "run_self_improvement_loop",
    "verification_profile_for_slice",
]
